import ele
import unyt as u

# Values as is from the paper.
# R in angstrom and D in kcal/mol

# Contains all info from Table I and Table II in the paper.
dreiding_atom_types = {
    "H_" : dict(
        vdw_r=3.195 * u.Angstrom,
        D=0.0152 * u.kcal,
        psi=12.382,
        bond_r=0.330 * u.Angstrom,
        theta=180.0 * u.deg,
        _def="[H;X1]",
        overrides="",
        desc="Hydrogen forming one bond",
        mass=ele.element_from_symbol("H").mass,
        element="H",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "H_HB": dict( # HB means hydrogen capable of forming hydrogen bonds
        vdw_r=3.195 * u.Angstrom,
        D=0.0001 * u.kcal,
        psi=12.0,
        bond_r=0.330 * u.Angstrom,
        theta=180.0 * u.deg,
        _def="[H;X1][N,O,F]",
        overrides="H_",
        desc="Hydrogen capable of hydrogen bonding",
        mass=ele.element_from_symbol("H").mass,
        element="H",
        doi="10.1021/j100389a010",
        is_metal=False,
    ), 
    "H_b": dict( # Bridging hydrogen atom in Diborane; H forms 2 bonds
        vdw_r=3.195 * u.Angstrom,
        D=0.0152 * u.kcal,
        psi=12.382,
        bond_r=0.510 * u.Angstrom,
        theta=90.0 * u.deg,
        _def="[H;X2]",
        overrides="H_",
        desc="Briding hydrogen with 2 bonds",
        mass=ele.element_from_symbol("H").mass,
        element="H",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "B": dict(
        vdw_r=4.02 * u.Angstrom,
        D=0.095 * u.kcal,
        psi=14.23,
        bond_r=0 * u.Angstrom,
        theta=0 * u.deg,
        _def="[B]",
        overrides="",
        desc="Boron",
        mass=ele.element_from_symbol("B").mass,
        element="B",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "B_2": dict(
        vdw_r=3.8983 * u.Angstrom,
        D=0.0951 * u.kcal,
        psi=14.034,
        bond_r=0.790 * u.Angstrom,
        theta=120 * u.deg,
        _def="[B;X3]",
        desc="Boron with 3 bonds",
        overrides="B",
        mass=ele.element_from_symbol("B").mass,
        element="B",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "B_3": dict(
        vdw_r=3.8983 * u.Angstrom,
        D=0.0951 * u.kcal,
        psi=14.034,
        bond_r=0.880 * u.Angstrom,
        theta=109.471 * u.deg,
        _def="[B;X4]",
        overrides="B",
        desc="Boron with 4 bonds",
        mass=ele.element_from_symbol("B").mass,
        element="B",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "C_1": dict(
        vdw_r=3.8983 * u.Angstrom,
        D=0.0951 * u.kcal,
        psi=14.034,
        bond_r=0.602 * u.Angstrom,
        theta=180 * u.deg,
        _def="[C;X2;!r6;!r5]",
        overrides="",
        desc="Linear carbon (sp1) with 2 bonds",
        mass=ele.element_from_symbol("C").mass,
        element="C",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "C_2": dict(
        vdw_r=3.8983 * u.Angstrom,
        D=0.0951 * u.kcal,
        psi=14.034,
        bond_r=0.670 * u.Angstrom,
        theta=120 * u.deg,
        _def="[C;X3;!r6;!r5]",
        overrides="",
        desc="Trigonal carbon (sp2) with 3 bonds, not in a ring",
        mass=ele.element_from_symbol("C").mass,
        element="C",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "C_3": dict(
        vdw_r=3.8983 * u.Angstrom,
        D=0.0951 * u.kcal,
        psi=14.034,
        bond_r=0.770 * u.Angstrom,
        theta=109.471 * u.deg,
        _def="[C;X4;!r6;!r5]",
        overrides="",
        desc="Tetrahedral carbon (sp3) with 4 bonds, not in a ring",
        mass=ele.element_from_symbol("C").mass,
        element="C",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "C_R": dict(
        vdw_r=3.8983 * u.Angstrom,
        D=0.0951 * u.kcal,
        psi=14.034,
        bond_r=0.700 * u.Angstrom,
        theta=120 * u.deg,
        _def="[C;r6]",
        overrides="C_2",
        desc="Carbon in a 6-membered ring",
        mass=ele.element_from_symbol("C").mass,        
        element="C",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "C_R5": dict(
        vdw_r=3.8983 * u.Angstrom,
        D=0.0951 * u.kcal,
        psi=14.034,
        bond_r=0.700 * u.Angstrom,
        theta=116 * u.deg, # Angle from OPLS-AA
        _def="[C;r5]",
        overrides="C_2, C_3",
        desc="Carbon in 5-membered rings",
        mass=ele.element_from_symbol("C").mass,
        element="C",
        doi="", # Added manually, theta taken from OPLS-AA
        is_metal=False,
    ),
    "N_1": dict(
        vdw_r=3.6621 * u.Angstrom,
        D=0.0774 * u.kcal,
        psi=13.843,
        bond_r=0.556 * u.Angstrom,
        theta=180 * u.deg,
        _def="[N;X2,X1;!r6;!r5]",
        overrides="",
        desc="Linear nitrogen with 2 bonds, or tripled bonded to 1 atom, not in a ring.",
        mass=ele.element_from_symbol("N").mass,
        element="N",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "N_2": dict(
        vdw_r=3.6621 * u.Angstrom,
        D=0.0774 * u.kcal,
        psi=13.843,
        bond_r=0.615 * u.Angstrom,
        theta=120 * u.deg,
        _def="[N;X3;!r6;!r5]",
        overrides="",
        desc="Trigonal nitrogen with 3 bonds, not in a ring",
        mass=ele.element_from_symbol("N").mass,
        element="N",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "N_3": dict(
        vdw_r=3.6621 * u.Angstrom,
        D=0.0774 * u.kcal,
        psi=13.843,
        bond_r=0.702 * u.Angstrom,
        theta=106.7 * u.deg,
        _def="[N;X4;!r6;!r5]",
        overrides="",
        desc="Tetrahedral nitrogen with 4 bonds, not in a ring",
        mass=ele.element_from_symbol("N").mass,
        element="N",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "N_R": dict(
        vdw_r=3.6621 * u.Angstrom,
        D=0.0774 * u.kcal,
        psi=13.843,
        bond_r=0.650 * u.Angstrom,
        theta=120 * u.deg,
        _def="[N;r6]",
        overrides="N_2, N_1",
        desc="Nitrogen in a 6-membered ring",
        mass=ele.element_from_symbol("N").mass,
        element="N",
        doi="10.1021/j100389a010",
        is_metal=False,
    ),
    "N_R5": dict(
        vdw_r=3.6621 * u.Angstrom,
        D=0.0774 * u.kcal,
        psi=13.843,
        bond_r=0.650 * u.Angstrom,
        theta=107.2 * u.deg,
        _def="[N;r5]",
        overrides="N_2, N_1",
        desc="Nitrogen in 5-membered rings",
        mass=ele.element_from_symbol("N").mass,
        element="N",
        doi="", # Added manually, use theta from OPLS-AA
        is_metal=False,
    ),
    "O_1": dict(
        vdw_r=3.4046 * u.Angstrom,
        D=0.0957 * u.kcal,
        psi=13.843,
        bond_r=0.528 * u.Angstrom,
        theta=180 * u.deg,
        _def="[O;X1;!r6;!r5]",
        overrides="",
        desc="Linear oxygen",
        element="O",
        mass=ele.element_from_symbol("O").mass,
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "O_2": dict(
        vdw_r=3.4046 * u.Angstrom,
        D=0.0957 * u.kcal,
        psi=13.843,
        bond_r=0.560 * u.Angstrom,
        theta=120 * u.deg,
        _def="[O;X2;!r6;!r5]",
        overrides="",
        desc="Trigonal oxygen, 3 bonds, not in a ring",
        mass=ele.element_from_symbol("O").mass,
        element="O",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "O_3": dict(
        vdw_r=3.4046 * u.Angstrom,
        D=0.0957 * u.kcal,
        psi=13.843,
        bond_r=0.660 * u.Angstrom,
        theta=104.51 * u.deg,
        _def="[O;X3;!r6;!r5]",
        overrides="",
        desc="Tetrahedral oxygen, not in a ring",
        mass=ele.element_from_symbol("O").mass,
        element="O",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "O_R": dict(
        vdw_r=3.4046 * u.Angstrom,
        D=0.0957 * u.kcal,
        psi=13.843,
        bond_r=0.790 * u.Angstrom,
        theta=120 * u.deg,
        _def="[O;r6]",
        overrides="O_2",
        desc="Oxygen in a 6-membered ring",
        mass=ele.element_from_symbol("O").mass,
        element="O",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "O_R5": dict(
        vdw_r=3.4046 * u.Angstrom,
        D=0.0957 * u.kcal,
        psi=13.843,
        bond_r=0.790 * u.Angstrom,
        theta=106.5 * u.deg,
        _def="[O;r5]",
        overrides="O_2",
        desc="Oxygen in 5-membered rings",
        mass=ele.element_from_symbol("O").mass,
        element="O",
        is_metal=False,
        doi="", # Added manually, theta taken from OPLS-AA
    ),
    "F_": dict(
        vdw_r=3.4720 * u.Angstrom,
        D=0.0725 * u.kcal,
        psi=14.444,
        bond_r=0.611 * u.Angstrom,
        theta=180 * u.deg,
        _def="[F]",
        overrides="",
        desc="Any fluorine atom",
        mass=ele.element_from_symbol("F").mass,
        element="F",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "Al3": dict(
        vdw_r=4.39 * u.Angstrom,
        D=0.31 * u.kcal,
        psi=12.0,
        bond_r=1.047 * u.Angstrom,
        theta=109.471 * u.deg,
        _def="[Al]",
        overrides="",
        desc="Any aluminum atom",
        mass=ele.element_from_symbol("Al").mass,
        element="Al",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),
    "Si3": dict(
        vdw_r=4.27 * u.Angstrom,
        D=0.31 * u.kcal,
        psi=12.0,
        bond_r=0.937 * u.Angstrom,
        theta=109.471 * u.deg,
        _def="[Si;X4,X3]", # Just change this to any Si?
        overrides="",
        desc="Tetrahedral silicon.",
        mass=ele.element_from_symbol("Si").mass,
        element="Si",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "P_3": dict(
        vdw_r=4.1500 * u.Angstrom,
        D=0.3200 * u.kcal,
        psi=12.0,
        bond_r=0.890 * u.Angstrom,
        theta=93.3 * u.deg,
        _def="[P]",
        overrides="",
        mass=ele.element_from_symbol("P").mass,
        element="P",
        desc="Any phosphorus",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "S_3": dict(
        vdw_r=4.0300 * u.Angstrom,
        D=0.3440 * u.kcal,
        psi=12.0,
        bond_r=1.040 * u.Angstrom,
        theta=92.1 * u.deg,
        _def="[S;!r5,!r6]",
        overrides="",
        mass=ele.element_from_symbol("S").mass,
        element="S",
        desc="Any sulfur not in a ring",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "S_R": dict(
        vdw_r=4.0300 * u.Angstrom,
        D=0.3440 * u.kcal,
        psi=12.0,
        bond_r=1.040 * u.Angstrom,
        theta=97.0 * u.deg, # Angle from OPLS-AA Carbon-Thiol sulfur-Carbon angle
        _def="[S;r5,r6]",
        overrides="S_3",
        desc="Heterocyclic sulfur",
        mass=ele.element_from_symbol("S").mass,
        element="S",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "Cl": dict(
        vdw_r=3.9503 * u.Angstrom,
        D=0.2833 * u.kcal,
        psi=13.861,
        bond_r=0.997 * u.Angstrom,
        theta=180 * u.deg,
        _def="[Cl]",
        overrides="",
        desc="Any chlorine atom",
        mass=ele.element_from_symbol("Cl").mass,
        element="Cl",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "Ga3": dict(
        vdw_r=4.39 * u.Angstrom,
        D=0.40 * u.kcal,
        psi=12.0,
        bond_r=1.210 * u.Angstrom,
        theta=109.471 * u.deg,
        _def="[Ga]",
        overrides="",
        desc="Any gallium atom",
        mass=ele.element_from_symbol("Ga").mass,
        element="Ga",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),    
    "Ge3": dict(
        vdw_r=4.27 * u.Angstrom,
        D=0.40 * u.kcal,
        psi=12.0,
        bond_r=1.210 * u.Angstrom,
        theta=109.471 * u.deg,
        _def="[Ge]",
        overrides="",
        desc="Any germanium atom",
        mass=ele.element_from_symbol("Ge").mass,
        element="Ge",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),    
    "As3": dict(
        vdw_r=4.15 * u.Angstrom,
        D=0.41 * u.kcal,
        psi=12.0,
        bond_r=1.210 * u.Angstrom,
        theta=92.1 * u.deg,
        _def="[As]",
        overrides="",
        desc="Any arsenic atom",
        mass=ele.element_from_symbol("As").mass,
        element="As",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),    
    "Se3": dict(
        vdw_r=4.03 * u.Angstrom,
        D=0.43 * u.kcal,
        psi=12.0,
        bond_r=1.210 * u.Angstrom,
        theta=90.6 * u.deg,
        _def="[Se]",
        overrides="",
        desc="Any selenium atom",
        mass=ele.element_from_symbol("Se").mass,
        element="Se",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),    
    "Br": dict(
        vdw_r=3.9 * u.Angstrom,
        D=0.37 * u.kcal,
        psi=12.0,
        bond_r=1.167 * u.Angstrom,
        theta=180.0 * u.deg,
        _def="[Br]",
        overrides="",
        desc="Any bromine atom",
        mass=ele.element_from_symbol("Br").mass,
        element="Br",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),    
    "In": dict(
        vdw_r=4.59 * u.Angstrom,
        D=0.55 * u.kcal,
        psi=12.0,
        bond_r=1.390 * u.Angstrom,
        theta=109.471 * u.deg,
        _def="[In]",
        overrides="",
        desc="Any indium atom",
        mass=ele.element_from_symbol("In").mass,
        element="In",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),    
    "Sn3": dict(
        vdw_r=4.47 * u.Angstrom,
        D=0.55 * u.kcal,
        psi=12.0,
        bond_r=1.373 * u.Angstrom,
        theta=109.471 * u.deg,
        _def="[Sn]",
        overrides="",
        desc="Any tin atom",
        mass=ele.element_from_symbol("Sn").mass,
        element="Sn",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),    
    "Sb3": dict(
        vdw_r=4.35 * u.Angstrom,
        D=0.55 * u.kcal,
        psi=12.0,
        bond_r=1.432 * u.Angstrom,
        theta=91.6 * u.deg,
        _def="[Sb]",
        overrides="",
        desc="Any antimony atom",
        mass=ele.element_from_symbol("Sb").mass,
        element="Sb",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),
    "Te3": dict(
        vdw_r=4.23 * u.Angstrom,
        D=0.57 * u.kcal,
        psi=12.0,
        bond_r=1.280 * u.Angstrom,
        theta=90.3 * u.deg,
        _def="[Te]",
        overrides="",
        desc="Any tellurium atom",
        mass=ele.element_from_symbol("Te").mass,
        element="Te",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),
    "I_": dict(
        vdw_r=4.15 * u.Angstrom,
        D=0.51 * u.kcal,
        psi=12.0,
        bond_r=1.360 * u.Angstrom,
        theta=180.0 * u.deg,
        _def="[I]",
        overrides="",
        desc="Any iodine atom",
        mass=ele.element_from_symbol("I").mass,
        element="I",
        is_metal=False,
        doi="10.1021/j100389a010",
    ),
    "Na": dict(
        vdw_r=3.144 * u.Angstrom,
        D=0.5 * u.kcal,
        psi=12.0,
        bond_r=1.860 * u.Angstrom,
        theta=90.0 * u.deg,
        _def="[Na]",
        overrides="",
        desc="Any sodium atom",
        mass=ele.element_from_symbol("Na").mass,
        element="Na",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),
    "Ca": dict(
        vdw_r=3.427 * u.Angstrom,
        D=0.05 * u.kcal,
        psi=12.0,
        bond_r=1.940 * u.Angstrom,
        theta=90.0 * u.deg,
        _def="[Ca]",
        overrides="",
        desc="Any calcium atom",
        mass=ele.element_from_symbol("Ca").mass,
        element="Ca",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),
    "Fe": dict(
        vdw_r=4.54 * u.Angstrom,
        D=0.055 * u.kcal,
        psi=12.0,
        bond_r=1.258 * u.Angstrom,
        theta=90.0 * u.deg,
        _def="[Fe]",
        overrides="",
        desc="Any iron atom",
        mass=ele.element_from_symbol("Fe").mass,
        element="Fe",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),
    "Zn": dict(
        vdw_r=4.54 * u.Angstrom,
        D=0.055 * u.kcal,
        psi=12.0,
        bond_r=1.330 * u.Angstrom,
        theta=109.471 * u.deg,
        _def="[Zn]",
        overrides="",
        desc="Any zinc atom",
        mass=ele.element_from_symbol("Zn").mass,
        element="Zn",
        is_metal=True,
        doi="10.1021/j100389a010",
    ),
}
